<a href="https://colab.research.google.com/github/minsuk-heo/tf2/blob/master/jupyter_notebooks/08.RNN_Cell.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from IPython.display import Image

In [2]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
  %tensorflow_version 2.x
except Exception:
  pass

In [25]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, SimpleRNN
from tensorflow.keras.models import Model
import numpy as np

In [23]:
# input shape
inputs = Input(shape=(1,2))
# output shape, return state, use tanh as activation function
output, state = SimpleRNN(3, return_state=True, activation='tanh')(inputs)
model = Model(inputs=inputs, outputs=[output, state])

In [24]:
# test input
data = np.array([[ [1,2] ]])
# print output, state
output, state = model.predict(data)
print("output: ",output)
print("state: ",state)

output:  [[ 0.59875816 -0.21488725  0.9868549 ]]
state:  [[ 0.59875816 -0.21488725  0.9868549 ]]


In [26]:
# weights for input
model.layers[1].weights[0]

<tf.Variable 'simple_rnn_6/kernel:0' shape=(2, 3) dtype=float32, numpy=
array([[ 0.52332866,  1.093852  ,  0.43632066],
       [ 0.08394015, -0.6560708 ,  1.0364058 ]], dtype=float32)>

In [27]:
# weights for state
model.layers[1].weights[1]

<tf.Variable 'simple_rnn_6/recurrent_kernel:0' shape=(3, 3) dtype=float32, numpy=
array([[-0.40553737,  0.33566958, -0.8502149 ],
       [-0.6421073 , -0.7666063 ,  0.00361326],
       [ 0.65056723, -0.5473945 , -0.52642334]], dtype=float32)>

In [28]:
# bias
model.layers[1].weights[2]

<tf.Variable 'simple_rnn_6/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

# POS tag example

In [30]:
# I      [1,0,0,0]
# work   [0,1,0,0]
# at     [0,0,1,0]
# google [0,0,0,1]
#
# I work at google =  [ [1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1] ]
# I google at work =  [ [1,0,0,0], [0,0,0,1], [0,0,1,0], [0,1,0,0] ]

data = np.array([
    [ [1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1] ],
    [ [1,0,0,0], [0,0,0,1], [0,0,1,0], [0,1,0,0] ]
])

In [31]:
# input shape
inputs = Input(shape=(4, 4))
# output shape, return state, return sequence
output, state = SimpleRNN(3, return_state=True, return_sequences=True)(inputs)
model = Model(inputs=inputs, outputs=[output, state])

In [32]:
# print output, state
output, state = model.predict(data)

In [34]:
print("I work at google: ",output[0])
print("I google at work: ",output[1])

I work at google:  [[-0.64201987 -0.57572216  0.66144264]
 [ 0.5993513   0.29302058  0.02963801]
 [ 0.19369544  0.1784203  -0.49658096]
 [-0.7203697   0.05810541  0.17543662]]
I google at work:  [[-0.64201987 -0.57572216  0.66144264]
 [-0.12968908  0.5340409   0.90266407]
 [-0.00650498  0.65877247  0.40018198]
 [-0.53214157 -0.11431938 -0.36563167]]


1. you can see first words(I) have same output because there is no previous state.
2. from second word you can see the output is different, because there is a previous state influences current state.

In [35]:
print("I work at google: state: ",state[0])
print("I google at work: state: ",state[1])

I work at google: state:  [-0.7203697   0.05810541  0.17543662]
I google at work: state:  [-0.53214157 -0.11431938 -0.36563167]


3. the last state is same with last output